name: Audit
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [13.12.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: lint
        run: npm run lint
  prettier:
    name: Prettier Check
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [13.12.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: lint
        run: npm run prettier
